/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Account: typeof import('./src/components/account/Account.vue')['default']
    AddOrganization: typeof import('./src/components/add-organization/AddOrganization.vue')['default']
    Home: typeof import('./src/components/home/Home.vue')['default']
    IconList: typeof import('./src/components/icons/IconList.vue')['default']
    IMdiCaretDown: typeof import('~icons/mdi/caret-down')['default']
    Login: typeof import('./src/components/login/Login.vue')['default']
    Nav: typeof import('./src/components/nav/Nav.vue')['default']
    Register: typeof import('./src/components/register/Register.vue')['default']
    Restore: typeof import('./src/components/restore/Restore.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/sidebar/SideBar.vue')['default']
  }
}
